package com.freelancewatermelon.twitterclientapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.freelancewatermelon.twitterclientapp.db.Tweets;

import com.freelancewatermelon.twitterclientapp.db.TweetsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tweetsDaoConfig;

    private final TweetsDao tweetsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tweetsDaoConfig = daoConfigMap.get(TweetsDao.class).clone();
        tweetsDaoConfig.initIdentityScope(type);

        tweetsDao = new TweetsDao(tweetsDaoConfig, this);

        registerDao(Tweets.class, tweetsDao);
    }
    
    public void clear() {
        tweetsDaoConfig.clearIdentityScope();
    }

    public TweetsDao getTweetsDao() {
        return tweetsDao;
    }

}
