package com.freelancewatermelon.twitterclientapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "TWEETS".
 */
@Entity
public class Tweets {

    @Id
    private Long id;

    @NotNull
    private String tweet_username;
    private String tweet_text;
    private String tweet_user_img;
    private String tweet_time;
    private String tweet_text_image;

    @Generated
    public Tweets() {
    }

    public Tweets(Long id) {
        this.id = id;
    }

    @Generated
    public Tweets(Long id, String tweet_username, String tweet_text, String tweet_user_img, String tweet_time, String tweet_text_image) {
        this.id = id;
        this.tweet_username = tweet_username;
        this.tweet_text = tweet_text;
        this.tweet_user_img = tweet_user_img;
        this.tweet_time = tweet_time;
        this.tweet_text_image = tweet_text_image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTweet_username() {
        return tweet_username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTweet_username(@NotNull String tweet_username) {
        this.tweet_username = tweet_username;
    }

    public String getTweet_text() {
        return tweet_text;
    }

    public void setTweet_text(String tweet_text) {
        this.tweet_text = tweet_text;
    }

    public String getTweet_user_img() {
        return tweet_user_img;
    }

    public void setTweet_user_img(String tweet_user_img) {
        this.tweet_user_img = tweet_user_img;
    }

    public String getTweet_time() {
        return tweet_time;
    }

    public void setTweet_time(String tweet_time) {
        this.tweet_time = tweet_time;
    }

    public String getTweet_text_image() {
        return tweet_text_image;
    }

    public void setTweet_text_image(String tweet_text_image) {
        this.tweet_text_image = tweet_text_image;
    }

}
